version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8443:8443
    volumes:
      - .:/app
    environment:
      APP_HOSTNAME: parking.xwysyy.cn
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: pk_db
      DB_USER: db_user
      DB_PASSWD: db_passwd
      MGR_NAME: admin
      MGR_PASSWD: admin
    networks:
      - app-net
    hostname: app
    command: bash -c "chmod +x runserver.sh && ./runserver.sh"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.4
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pk_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_passwd
    ports:
      - 3308:3306
    networks:
      - app-net
    hostname: mysql
    restart: always

  web-nginx:
    image: nginx:alpine
    privileged: true
    environment:
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./Web/nginx.conf:/etc/nginx/conf.d/my.conf
      - ./Web/dist:/usr/share/nginx/html
      - ./Web/cert:/etc/nginx/cert
    networks:
      - app-net
    ports:
      - '8444:443'

  adminer:
    image: adminer:latest
    ports:
      - 8441:8080
    networks:
      - app-net
    hostname: adminer
    restart: always

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.254.0/24